[IMP] iot_template_oca: add iot.device.configure access rules
OCA/iot pull request #48
Opened 2021-12-20 12:50 UTC by olgamarcocb

2021-12-20 16:55 UTC, lubusax approved these changes

2021-12-20 16:56 UTC, pedrobaeza commented
Why do you need this?

2021-12-20 17:33 UTC, etobella commented
Wizards must have security groups and this one was missing

2021-12-20 17:34 UTC, etobella requested changes

2021-12-20 17:34 UTC, etobella commented on iot_template_oca/security/ir.model.access.csv
> +access_iot_device_configure,access_iot_device_configure,model_iot_device_configure,base.group_user,1,0,0,0
Iot manager better

2021-12-20 17:35 UTC, pedrobaeza commented
A healthy habit is to give these explanations about the whys in the commit message extended text.

2021-12-21 08:59 UTC, etobella requested changes

2021-12-21 08:59 UTC, etobella commented on iot_template_oca/security/ir.model.access.csv
> +access_iot_device_configure,access_iot_device_configure,model_iot_device_configure,iot_oca.group_iot_manager,1,0,0,0
permissions should be 1,1,1,1

2021-12-21 09:03 UTC, olgamarcocb commented on iot_template_oca/security/ir.model.access.csv
> +access_iot_device_configure,access_iot_device_configure,model_iot_device_configure,iot_oca.group_iot_manager,1,0,0,0
Done!

2021-12-21 09:04 UTC, etobella approved these changes

2021-12-21 09:05 UTC, etobella commented
/ocabot merge patch

2021-12-21 09:06 UTC, olgamarcocb commented
@pedrobaeza sorry for the trouble. I will improve my commit messages.

2021-12-21 09:07 UTC, merged