[16.0] [MIG] iot_oca: Migration to 16.0
OCA/iot pull request #84
Opened 2023-04-21 20:35 UTC by mostafabarmshory

I try to migrate IoT module from 15 to 16. Here is the guide line

https://github.com/OCA/maintainer-tools/wiki/Migration-to-version-16.0

2023-04-21 20:40 UTC, mostafabarmshory commented
Dear @etobella and @pedrobaeza :

I followed the guideline and moved a single (core addon). Others depend on this and I have to wait for it. Would you check and accept the pull? please.

2023-04-26 00:39 UTC, mostafabarmshory commented
Dear @etobella ,
Would you check the PR and provide feedback to me, please? I`ve followed instructions step by step. Other add-ons depend on this one and I need it to continue.

2023-04-26 09:44 UTC, etobella requested changes

2023-04-26 09:44 UTC, etobella commented on iot_oca/tests/test_iot.py
> +    os.system("pip install mock")
Don't do that

Keep as 

`from mock import patch`

If you don't have this installed, the only problem will be a failure in test, and that is not important.

2023-04-27 08:47 UTC, mostafabarmshory commented on iot_oca/tests/test_iot.py
> +    os.system("pip install mock")
Ok, bro.
Tests failed in my development environment. I guess they fail on GitHub too. 

np, I fix this right now.

2023-04-27 10:03 UTC, mostafabarmshory commented
Dear @etobella 
as you see all test fails. We need the mock module just in the development environment. I can't find a way to add the dependency just for tests. 

Could you help me to solve the issue, please?

2023-04-27 10:16 UTC, etobella commented
pre-commit fails due to some linting errors. intstall pre-commit on your environment.

If you need a testing library add it to test-requirements.txt file on the main folder. Something like this:

https://github.com/OCA/purchase-workflow/blob/c186f0808b932416bb5e1cab563cfd87c2ee4d3b/test-requirements.txt#L1

2023-04-27 11:46 UTC, mostafabarmshory commented
@etobella 
finally, all checks passed.

2023-04-27 12:48 UTC, etobella commented
Can you squash all your commits?

2023-04-29 14:16 UTC, mostafabarmshory commented
Closed due to https://github.com/OCA/iot/pull/85

2023-04-29 14:16 UTC, closed without merging