[16.0] [MIG] iot_output_oca: Migration to 16.0
OCA/iot pull request #88
Opened 2023-06-21 17:10 UTC by mostafabarmshory

2023-06-23 09:47 UTC, flotho commented
Hi,
AFAICS, there is no menu for setting up output actions, could you : 
* document the process to add an action to an output
* maybe add a menu
* maybe add demo datas,

Thanks for your work

2023-06-23 09:48 UTC, flotho requested changes
see my previous comment

2023-06-24 06:26 UTC, mostafabarmshory commented
Actually, IoT input and output are an abstraction of how things send and receive messages. Others create an input-output. So you must install MQTT for example to have input output.

Specially output one.

I hope we develop a site for IoT and put documents there.

However, I can launch a website on my own workspace and publish documents there. 

If you agree let me know.

@flotho

2023-06-27 07:49 UTC, flotho commented
Hi @mostafabarmshory , thanks for your reply,
IMHO, you can start by explaining in the README what you wrote here, it will be a good starting point for new users like me.

2023-06-27 08:19 UTC, mostafabarmshory commented
@etobella 

Would you check if is everything ok, please? Then I`ll squish them all in one commit.

2023-06-27 09:50 UTC, etobella commented
Migration seems ok. You need to change the commit description.

About @flotho comments, it would be great if you are able to add the info on the readme :smile:

2023-06-27 13:43 UTC, mostafabarmshory commented
@flotho  @etobella 

I have a tiny execution plan. But at the first step, I have to move all addons into 16 then.

@etobella would you check the PR, please?

2023-06-27 14:12 UTC, etobella approved these changes

2023-06-27 14:15 UTC, mostafabarmshory commented
/ocabot merge nobump

2023-06-27 14:19 UTC, sanchonuria approved these changes

2023-06-27 14:19 UTC, etobella commented
@mostafabarmshory you cannot do a merge if you are not an official maintainer of the repo or module

Don't worry

/ocabot migration iot_output_oca
/ocabot merge nobump

2023-06-27 14:24 UTC, merged